In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from Bio import SeqIO

In [2]:
saureus_path = "../data/staph/saureus.fa"
saureus_count = 0

for record in SeqIO.parse(saureus_path, "fasta"):
    print(record.id, len(record.seq))
    saureus_count += 1

print(f"Total number of S. aureus sequences: {saureus_count}")

C1075 2902619
C1076 2902619
C1077 2902619
C1078 2902619
C1079 2902619
C1080 2902619
C1081 2902619
C1082 2902619
C1083 2902619
C1084 2902619
C1085 2902619
C1087 2902619
C1088 2902619
C1089 2902619
C1090 2902619
C1091 2902619
C1092 2902619
C1093 2902619
C1094 2902619
C1095 2902619
C1096 2902619
C1097 2902619
C1098 2902619
C1099 2902619
C1100 2902619
C1101 2902619
C1102 2902619
C1103 2902619
C1104 2902619
C1105 2902619
C1106 2902619
C1107 2902619
C1108 2902619
C1110 2902619
C1111 2902619
C1112 2902619
C1113 2902619
C1114 2902619
C1115 2902619
C1116 2902619
C1117 2902619
C1118 2902619
C1119 2902619
C1120 2902619
C1121 2902619
C1122 2902619
C1123 2902619
C1124 2902619
C1125 2902619
C1126 2902619
C1127 2902619
C1128 2902619
C1129 2902619
C1130 2902619
C1131 2902619
C1132 2902619
C1134 2902619
C1135 2902619
C1136 2902619
C1137 2902619
C1139 2902619
C1140 2902619
C1141 2902619
C1142 2902619
C1143 2902619
C1144 2902619
C1146 2902619
C1147 2902619
C1148 2902619
C1149 2902619
C1150 2902619
C1151 2902619
C1152 2902619
C1153 2902619
C1154 2902619
C1155 2902619
C1156 2902619
C1157 2902619
C1158 2902619
C1159 2902619
C1160 2902619
C1161 2902619
C1162 2902619
C1163 2902619
C1164 2902619
C1165 2902619
C1274 2902619
C1275 2902619
C1276 2902619
C1277 2902619
C1278 2902619
C1279 2902619
C1280 2902619
C1281 2902619
C1282 2902619
C9655 2902619
C9656 2902619
C9657 2902619
C9658 2902619
C9659 2902619
C9660 2902619
C9662 2902619
C9663 2902619
C9664 2902619
C9665 2902619
C9666 2902619
C9667 2902619
C9668 2902619
C9669 2902619
C9670 2902620
Total number of S. aureus sequences: 110

In [3]:
core_path = "../data/staph/core_CDS_all.fa"
core_count = 0
core_lengths = []

for record in SeqIO.parse(core_path, "fasta"):
    print(record.id, len(record.seq))
    core_count += 1
    core_lengths.append(len(record.seq))

print(f"Total number of core sequences: {core_count}")

dnaA 1362
dnaN 1134
SAR0003 246
recF 1113
gyrB 1932
gyrA 2661
SAR0007 831
hutH 1515
serS 1287
SAR0010 696
SAR0011 330
SAR0012 969
SAR0013 987
SAR0014 1968
rplI 447
dnaC 1401
purA 1284
yycF 708
yycG 1827
yycH 1335
yycI 789
yycJ 801
sasH 2361
SAR0024 480
SAR0100 162
SAR0104 483
plc 987
SAR0107 2238
SAR0108 1179
SAR0109 1389
SAR0110 1668
SAR0111 1776
SAR0112 474
lldP1 1593
SAR0115 753
sirC 999
sirA 993
SAR0119 981
SAR0120 1011
SAR0121 1755
SAR0123 1737
SAR0124 1779
SAR0125 777
SAR0126 1203
SAR0127 765
SAR0129 777
SAR0130a 114
SAR0130 972
SAR0131 690
SAR0132 1167
SAR0133 1239
SAR0134 1431
sodM 600
SAR0137 741
deoD1 708
SAR0139 1353
drm 1179
SAR0144 774
SAR0145 957
SAR0146 1545
SAR0147 1536
capA 669
capB 687
capC 765
capD 1824
capE 1029
capF 1110
capG 1125
capL 1206
capM 558
capN 888
capO 1263
capP 1176
SAR0167 327
SAR0168 384
SAR0169 1488
SAR0171 204
SAR0172 513
SAR0173 741
SAR0174 975
SAR0175 762
SAR0176 1032
SAR0180 7176
SAR0181 645
SAR0182 495
argJ 1242
argC 1035
SAR0186 1185
SAR0187 1356
SAR0188 558
SAR0189 1641
glcA 2046
SAR0191 1056
SAR0192 900
SAR0193 1455
SAR0194 879
SAR0196 2790
SAR0198 1593
SAR0199 1308
rlp 1776
SAR0203 627
SAR0204 579
SAR0205 1098
SAR0206 1272
SAR0207 1269
SAR0208 840
SAR0209 1080
SAR0210 1041
SAR0211 969
SAR0212 495
uhpT 1380
SAR0214 759
SAR0215 1557
SAR0216 969
SAR0217 2250
SAR0218 756
SAR0219 168
SAR0220 1764
SAR0221 345
fadD 1212
fadE 1506
fadX 1563
SAR0229 1143
SAR0230 1476
SAR0231 357
SAR0232 174
SAR0233 1146
ldh1 954
SAR0235 1530
SAR0236 936
SAR0238 2097
SAR0240 468
SAR0241 279
SAR0242 1260
SAR0243 1056
SAR0244 147
SAR0245 1044
SAR0247 1026
SAR0251 1170
SAR0252 717
SAR0253 1026
SAR0255 1725
scdA 675
lytS 1755
lytR 741
lrgA 444
lrgB 702
SAR0262 705
SAR0263 792
bglA 1437
SAR0265 762
SAR0266 915
SAR0267 405
SAR0268 882
SAR0269 999
SAR0271 1377
SAR0272 993
lytM 951
SAR0274 660
SAR0275 921
SAR0276 1167
SAR0277 1524
SAR0303 1308
SAR0304 891
SAR0305 1050
SAR0306 678
SAR0308 1119
SAR0309 924
SAR0310 1221
SAR0312 882
SAR0313 861
SAR0314 801
SAR0315 669
SAR0318 828
SAR0319 1215
SAR0320 1002
SAR0321 333
SAR0322 801
SAR0323 948
SAR0324 1023
SAR0326 1347
SAR0327 285
SAR0328 444
SAR0329 1956
SAR0330 420
SAR0331 1356
SAR0332 441
glpT 1359
SAR0335 1062
SAR0336 567
SAR0338 996
SAR0339 546
SAR0340 855
SAR0341 1230
SAR0342 1713
SAR0343 702
SAR0344 216
SAR0345 390
SAR0348 843
SAR0349 630
SAR0350 1134
thl 1182
SAR0352 753
metE 2229
SAR0354 1842
SAR0355 1161
SAR0356 1104
SAR0357 846
SAR0358 882
SAR0359 204
SAR0360 1098
SAR0361 192
rpsF 297
rpsR 243
SAR0389 369
SAR0390 573
SAR0391 264
SAR0392 255
SAR0393 210
SAR0394 582
SAR0395 384
SAR0396 627
ahpF 1524
ahpC 570
SAR0400 756
SAR0401a 102
SAR0403 957
SAR0404 663
SAR0405 408
xpt 579
guaB 1467
guaA 1542
SAR0418 162
SAR0420 360
SAR0421 846
SAR0422 681
set3 705
SAR0437 309
SAR0447 324
SAR0449 195
SAR0450 1203
SAR0452 1485
SAR0454 363
SAR0455 348
SAR0456 675
SAR0457 735
SAR0458 1341
SAR0459 906
SAR0460 1143
SAR0464 1005
SAR0465 270
SAR0466 405
SAR0467 486
SAR0468 783
SAR0469 1119
SAR0470 885
SAR0473 1428
SAR0474 1641
SAR0475 729
SAR0475a 66
SAR0476 525
dnaX 1698
SAR0478 318
recR 597
SAR0482 1338
tmk 618
SAR0484 330
holB 927
SAR0486 804
SAR0487 348
SAR0488 726
SAR0489 249
SAR0490 840
SAR0492 774
SAR0494 894
veg 264
SAR0496 849
purR 825
yabJ 381
spoVG 303
gcaD 1353
prs 966
rplY 654
SAR0503 573
SAR0504 3507
SAR0505 1527
SAR0506 1194
SAR0507 264
SAR0508 393
SAR0509 402
SAR0510 1296
hpt 540
ftsH 2094
SAR0513 882
SAR0514 933
folP 804
folB 366
folK 477
lysS 1488
SAR0521 1383
SAR0522 888
SAR0523 561
nupC 1215
SAR0525 462
SAR0526 567
SAR0527 1008
clpC 2457
radA 1365
SAR0530 1074
gltX 1455
cysE 648
cysS 1401
SAR0534 405
yacO 747
SAR0536 525
sigH 570
rpmG3 144
secE 183
nusG 549
rplK 423
rplA 690
rplJ 501
SAR0546 609
rpoB 3552
rpoC 3624
SAR0549 312
rpsL 414
rpsG 471
fus 2082
tuf 1185
SAR0554 1176
kbl 1188
SAR0556 879
SAR0557 1638
SAR0558 966
SAR0559 1077
SAR0560 684
SAR0561 663
SAR0562 618
SAR0563 471
SAR0564 870
SAR0565 567
SAR0568 1473
SAR0569 1491
SAR0570 879
SAR0571 666
SAR0572 360
SAR0573 759
SAR0574 633
SAR0575 549
SAR0576 648
proP 1401
SAR0578 294
SAR0580 1377
SAR0582 366
SAR0583 270
SAR0584 168
SAR0585 831
ung 657
SAR0587 381
SAR0588 369
SAR0589 1485
SAR0591 765
SAR0593 753
pta 987
SAR0595 837
mvaK1 921
mvaK2 1077
SAR0599 342
SAR0600 1323
SAR0601 441
SAR0602 1395
SAR0608 939
SAR0609 537
SAR0610 477
SAR0611 1296
SAR0612 507
adhA 1011
SAR0614 429
argS 1662
SAR0618 888
SAR0619 951
SAR0620 720
SAR0621 801
SAR0622 507
SAR0623 717
SAR0624 789
sarA 375
SAR0626 930
SAR0627 225
SAR0629 561
SAR0630 2403
SAR0634 483
SAR0635 303
SAR0636 438
SAR0637 2043
SAR0641 930
SAR0642 837
SAR0643 744
sirR 645
tagA 765
tagH 795
tagG 834
tagB 1104
SAR0650 1062
tagD 399
pbp4 1296
SAR0653 1728
SAR0654 81
SAR0655 1230
SAR0656 834
fhuA 798
fhuB 1005
fhuD 1017
SAR0660 969
SAR0661 585
SAR0662 363
SAR0663 498
SAR0664 1068
SAR0665 1044
SAR0666 429
SAR0667 507
SAR0668 924
SAR0669 675
SAR0670 1041
SAR0671 762
SAR0672 1890
SAR0673 618
SAR0674 1008
SAR0675 798
SAR0676 645
SAR0679 426
SAR0680 717
SAR0681 474
SAR0682 645
SAR0683 867
SAR0684 1221
SAR0728 690
SAR0729 444
SAR0730 390
SAR0731 300
SAR0732 543
SAR0733 567
SAR0734 459
bacA 876
SAR0737 1632
SAR0738 1674
SAR0739 444
SAR0740 927
SAR0741 909
SAR0742 288
SAR0743 1554
SAR0744 1374
SAR0747 423
norA 1167
SAR0749 465
SAR0751 762
SAR0752 921
SAR0754 1182
SAR0755 1350
SAR0756 840
saeS 1056
saeR 687
SAR0760 474
SAR0761 441
SAR0762 585
SAR0763 714
SAR0764 420
SAR0765 669
SAR0766 594
SAR0767 1152
SAR0768 609
SAR0769 207
SAR0770 711
SAR0771 1005
SAR0772 1941
SAR0773 1878
SAR0774 1782
SAR0775 978
SAR0776 1515
SAR0777 1059
SAR0778 543
SAR0780 918
SAR0781 1506
SAR0782 501
SAR0783 867
SAR0784 399
rir1 2106
rir2 972
sstA 972
sstB 957
sstD 1029
SAR0791 315
murB 924
SAR0793 519
SAR0794 879
SAR0795 321
SAR0796 1125
pepT 1227
SAR0798 495
SAR0799 762
SAR0800 1071
SAR0801 1056
SAR0802 642
SAR0803 867
SAR0804 1083
SAR0805 675
secA 2532
prfB 1111
SAR0809 840
SAR0810 651
SAR0811 237
uvrB 1992
uvrA 2847
hprK 933
SAR0816 486
SAR0817 1440
trxB 936
SAR0820 912
SAR0821 996
SAR0822 945
clpP 588
SAR0825 903
SAR0826 630
gapR 1014
gap1 1011
pgk 1191
tpiA 762
pgm 1518
eno 1305
SAR0833 459
secG 234
est 741
rnr 2373
smpB 465
SAR0845 1026
nuc 687
cspC 201
SAR0849 219
SAR0850 285
SAR0851 570
SAR0852 189
SAR0853 261
SAR0854 204
SAR0855 237
SAR0856 582
SAR0857 618
SAR858a 51
SAR0859 423
SAR0860 717
SAR0861 540
SAR0862 321
SAR0863 357
gcvH 381
SAR0867 387
SAR0868 297
SAR0870 1026
SAR0871 696
SAR0872 822
SAR0875 852
SAR0876 762
SAR0877 1308
csdB 1242
SAR0879 465
SAR0880 1398
SAR0881 315
SAR0884 849
SAR0885 828
SAR0886 1320
lipA 918
SAR0888 384
SAR0889 267
SAR0890 435
SAR0891 780
SAR0892 960
SAR0893 153
dltA 1458
dltB 1215
dltC 237
dltD 1176
SAR0898 243
SAR0900 1065
SAR0901 237
SAR0902 360
SAR0903 1209
pepA 1476
SAR0905 1317
SAR0906 375
SAR0907 1155
mnhG 357
mnhF 294
mnhE 480
mnhD 1497
mnhC 342
mnhB 429
mnhA 2406
SAR0915 384
SAR0916 594
SAR0917 378
rocD 1191
SAR0920 1245
glpQ 930
argH 1380
argG 1206
SAR0924 1332
SAR0925 576
spsA 525
spsB 576
SAR0928 3477
SAR0929 3654
SAR0930 903
SAR0931 390
SAR0933 1317
SAR0935 309
SAR0937 1815
clpB 2610
SAR0939 870
SAR0943 516
SAR0944 435
SAR0945 186
fabH 942
fabF 1245
oppB 927
oppC 1071
oppD 1083
oppF 942
SAR0953 1656
trpS 990
SAR0965 396
SAR0966 720
SAR0967 987
pepB 1809
SAR0969 807
SAR0970 366
SAR0971 594
SAR0972 348
SAR0973 636
SAR0974 810
SAR0975 855
SAR0976 1386
SAR0977 1845
fabI 771
SAR0979 1086
SAR0980 1569
SAR0981 759
SAR0985 510
SAR0987 1176
murE 1485
SAR0989 252
prfC 1563
SAR0991 804
SAR0992 2310
SAR0993 1359
SAR0994 1515
SAR0995 570
SAR0996 228
SAR0997 987
SAR0998 177
SAR0999 603
SAR1000 180
SAR1003 321
SAR1005 291
SAR1010 357
SAR1011 960
SAR1012 117
SAR1013 216
SAR1014 552
SAR1015 939
SAR1016 1371
SAR1018 804
menB 822
sspC 330
sspB 1182
SAR1023 1155
SAR1024 1012
SAR1025 420
SAR1027 435
SAR1028 471
SAR1029 1227
fmt 1194
qoxD 291
qoxC 606
qoxB 1989
SAR1035 318
folD 861
purE 483
purK 1125
purC 705
SAR1041 264
purQ 672
purF 1485
purM 1029
purN 567
purH 1479
SAR1049 822
SAR1050 1401
SAR1051 576
SAR1053 1296
SAR1055 543
ptsH 267
ptsI 1719
SAR1058 234
SAR1059 1362
SAR1060 1020
SAR1061 663
SAR1063 1698
SAR1064 219
SAR1065 552
SAR1066 627
pdhA 1113
pdhB 978
pdhC 1293
pdhD 1407
SAR1071 276
SAR1072 540
SAR1073 1095
SAR1074 798
SAR1075 810
SAR1076 1074
SAR1077 1020
SAR1078 420
SAR1079 1353
SAR1080 615
SAR1081 828
SAR1082 192
SAR1084 168
SAR1085 483
SAR1086 276
SAR1088 3453
ctaA 912
ctaB 912
SAR1091 462
SAR1092 1038
SAR1093 435
SAR1094 930
SAR1095 255
SAR1096 390
SAR1097 543
coaD 483
SAR1099 1140
SAR1100 558
rpmF 174
isdB 1959
isdA 1065
isdC 684
isdD 1077
isdE 879
srtB 735
SAR1109 324
SAR1110 741
pheS 1059
SAR1113 939
SAR1114 267
SAR1115 522
SAR1116 1713
SAR1117 2349
trxA 315
uvrC 1782
sdhC 615
sdhA 1767
sdhB 816
murI 801
SAR1124 588
SAR1125 504
SAR1126 168
SAR1127 318
SAR1129 507
SAR1141 726
otc 1002
SAR1144 1557
SAR1146 228
SAR1147 948
SAR1148 198
SAR1150 135
SAR1151 687
SAR1152 441
SAR1153 1614
SAR1154 432
SAR1155 936
SAR1156 402
pbpA 2235
mraY 966
murD 1350
SAR1160 1323
ftsA 1407
ftsZ 1173
SAR1163 792
SAR1164 675
SAR1165 564
SAR1166 291
SAR1167 807
SAR1168 597
ileS 2754
SAR1171 798
lspA 492
SAR1173 918
pyrR 528
pyrP 1308
pyrB 882
pyrC 1275
pyrAA 1101
pyrAB 3174
pyrF 696
pyrE 612
SAR1182 213
SAR1183 402
SAR1184 1698
SAR1185 624
SAR1186 219
SAR1187 1200
SAR1190 279
def 489
SAR1192 936
SAR1193 1308
SAR1194 1095
SAR1195 744
pknB 1995
SAR1197 876
SAR1198 645
SAR1199 642
rpmB 189
SAR1201 375
SAR1202 1647
recG 2061
SAR1204 558
SAR1205 987
fabD 927
fabG 741
acpP 234
SAR1209 732
SAR1210 3567
SAR1211 1251
SAR1212 333
ffh 1368
rpsP 276
rimM 504
trmD 738
rplS 351
SAR1218 2607
rnhB 768
SAR1221 1167
SAR1222 909
topA 2070
SAR1227 1308
SAR1228 897
hslV 546
SAR1230 1404
codY 774
rpsB 768
tsf 882
pyrH 723
frr 555
uppS 771
SAR1237 783
SAR1238 1287
polC 4317
SAR1241 468
nusA 1176
SAR1243 285
SAR1244 318
infB 2118
rbfA 351
SAR1247 918
SAR1248 972
rpsO 270
pnpA 2097
SAR1251 1674
SAR1252 2370
SAR1253 714
SAR1254 1266
SAR1256 705
SAR1257 828
SAR1258 393
pgsA 579
SAR1260 1152
recA 1044
SAR1262 1560
SAR1263 171
SAR1264 798
SAR1265 1761
SAR1266 867
SAR1267 294
SAR1268 1545
SAR1269 366
SAR1270 492
mutS 2619
mutL 2010
glpP 534
SAR1273a 99
glpF 819
glpK 1497
glpD 1722
SAR1277 915
miaA 936
SAR1279 234
SAR1280 477
SAR1281 1239
SAR1282 1239
glnR 369
glnA 1341
SAR1325b 111
SAR1326 1026
SAR1327 198
SAR1328 1482
SAR1333 189
nucI 534
SAR1335 855
SAR1336 591
SAR1337 1395
SAR1338 1281
thrC 1062
thrB 915
SAR1341 804
SAR1342 315
SAR1343 1455
SAR1344 1518
rpmG2 150
SAR1346 270
SAR1347 978
SAR1348 864
dinR 624
SAR1350 237
SAR1351 240
SAR1352 1989
SAR1353 243
SAR1355 468
SAR1356 1122
SAR1357 3030
mscL 363
opuD1 1647
citB 2706
SAR1363 468
SAR1364 297
SAR1365 609
grlB 1998
grlA 2403
SAR1369 852
SAR1370 96
SAR1371 1209
mprF 2523
msrA1 510
SAR1374 984
SAR1376 189
SAR1377 1263
SAR1378 1092
SAR1379 1032
trpE 1407
trpG 567
trpD 997
trpC 783
trpF 633
trpB 1215
femA 1263
femB 1260
SAR1389 769
SAR1391 459
SAR1393 774
SAR1396 345
SAR1397 1815
SAR1398 642
SAR1399 852
SAR1400 918
SAR1401 927
SAR1403 903
SAR1404 1602
lysC 1206
asd 990
dapA 888
dapB 723
SAR1410 1152
dal 1086
lysA 1266
SAR1413 402
cspA 201
SAR1415 309
SAR1416 270
SAR1417 624
SAR1418 1137
SAR1419 1344
SAR1421 792
SAR1422 204
SAR1423 810
odhB 1272
arlS 1356
arlR 660
SAR1428 174
SAR1429 615
murG 1071
SAR1431 510
SAR1432 1491
SAR1434 222
SAR1435 501
msrA2 534
SAR1438 840
dfrB 480
thyA 957
SAR1441 438
SAR1442 1125
SAR1443 252
SAR1444 195
SAR1445 705
SAR1446 402
SAR1448 1392
SAR1449 1323
tdcB 1041
ald2 1119
SAR1452 879
SAR1453 3441
SAR1454 1342
SAR1455 333
SAR1456 1146
SAR1457 345
SAR1458 564
SAR1459 351
SAR1459a 171
recU 627
pbp2 2151
SAR1462 342
SAR1463 660
SAR1464 687
asnS 1293
SAR1466 2694
birA 972
papS 1203
SAR1469 1143
SAR1470 318
SAR1471 699
SAR1473 576
SAR1474 1245
aroA 1299
aroB 1065
aroC 1167
ndk 450
SAR1479 960
menH 726
SAR1481 573
hup 273
gpsA 999
SAR1484 1311
SAR1485 1176
cmk 660
SAR1487 969
SAR1488 987
SAR1490 1380
SAR1491 954
SAR1492 249
SAR1493 546
srrB 1767
srrA 744
rluB 738
SAR1570 543
SAR1571 756
SAR1572 507
xerD 888
fur 450
SAR1575 543
SAR1576 909
SAR1577 249
SAR1578 759
SAR1579 816
SAR1581 921
zwf 1485
SAR1583 867
malA 1650
malR 1020
SAR1586 372
gnd 1407
SAR1591 981
SAR1592 438
bfmB 1275
bfmBAB 984
bfmBAA 993
bfmBC 1422
SAR1597 1680
argR 453
SAR1599 882
SAR1600 231
SAR1601 1338
SAR1602 390
SAR1603 363
accB 465
efp 558
SAR1607 1062
SAR1608 582
SAR1609 219
SAR1610 831
SAR1611 387
SAR1612 1473
SAR1613 1356
gcvT 1092
SAR1615 525
SAR1616 498
SAR1617 300
SAR1618 435
SAR1619 312
SAR1620 1071
SAR1621 975
SAR1622 624
SAR1623 330
glkA 987
SAR1625 204
SAR1626 1464
SAR1627 540
rpmG1 150
pbpF 2076
sodA 600
zur 411
mreB 864
mreA 786
SAR1636 1101
SAR1637 678
rpoD 1107
dnaG 1800
SAR1640 819
SAR1641 634
SAR1642 1392
SAR1643 753
era 900
cdd 405
SAR1646 345
SAR1647 468
SAR1648 948
SAR1649 699
SAR1650 990
SAR1651 708
rpsU 177
SAR1653 1347
SAR1654 753
SAR1655 939
dnaK 1833
grpE 627
hrcA 978
SAR1660 1125
lepA 1824
rpsT 252
SAR1664 975
SAR1665 2202
SAR1666 462
SAR1667 678
SAR1668 717
SAR1669 354
SAR1670 585
SAR1671 570
SAR1672 291
aroE 807
SAR1674 1101
SAR1675 528
pfs 687
SAR1677 270
SAR1679 753
SAR1683 1233
SAR1684 753
SAR1686 450
SAR1687 1011
SAR1688 735
greA 477
udk 624
SAR1691 1269
SAR1692 924
SAR1693 639
SAR1694 309
SAR1695 429
SAR1696 261
alaS 2631
SAR1698 2478
SAR1699 669
SAR1701 1119
SAR1702 1143
SAR1703 1014
SAR1705 183
SAR1706 423
SAR1707 1275
SAR1708 774
SAR1709 102
aspS 1767
hisS 1263
SAR1712 875
SAR1713 453
relA 2211
apt 519
SAR1716 2274
secF 2280
SAR1718 261
tgt 1140
queA 1026
ruvB 1005
ruvA 603
SAR1723 459
obg 1293
rpmA 285
SAR1726 321
rplU 309
SAR1728 531
SAR1729 843
SAR1729a 120
SAR1730 474
SAR1731 216
SAR1732 285
SAR1741 708
folC 1272
valS 2631
hemL 1287
hemB 975
hemD 669
hemC 927
SAR1751 816
hemA 1347
SAR1753 591
clpX 1263
tig 1302
SAR1756 930
SAR1757 609
rplT 357
rpmI 201
infC 528
lysP 1494
thrS 1938
dnaI 921
dnaB 1401
SAR1765 471
gap2 1026
coaE 624
SAR1768 873
polA 2631
phoR 1665
phoP 702
citC 1269
citZ 1122
cycA 1362
pyk 1758
pfkA 969
accA 945
accD 858
SAR1780 1230
dnaE 3198
SAR1782 942
SAR1783 1299
SAR1784 414
SAR1785 690
SAR1786 1056
ald1 1119
SAR1788 501
ackA 1203
SAR1790 948
SAR1791 495
SAR1792 771
thiI 1224
SAR1794 1140
SAR1795 1695
SAR1796 465
rpsD 603
SAR1798 744
SAR1799 447
SAR1800 1161
SAR1801 1605
SAR1802 1131
SAR1803 1467
SAR1804 618
SAR1805 1275
tyrS 1263
SAR1807 906
harA 2673
SAR1809a 96
fhs 1668
acsA 1707
acuA 633
SAR1813 1170
ccpA 990
SAR1815 1092
SAR1817 492
murC 1314
SAR1819 3825
SAR1821 858
SAR1822 312
SAR1823 1077
SAR1824 312
SAR1825 843
SAR1833 645
SAR1834 792
dat 849
SAR1836 1410
SAR1837 423
SAR1838 696
SAR1839 1662
SAR1840 1269
SAR1842 312
leuS 2415
SAR1845 954
SAR1846 564
rot 501
SAR1848 828
SAR1849 1002
ribH 465
ribA 1182
ribE 633
ribD 1044
SAR1854 1503
arsR2 315
arsB2 1293
SAR1857 855
SAR1858 225
SAR1859 471
SAR1861 444
SAR1864 714
SAR1865 303
SAR1866 444
SAR1867 354
SAR1868 834
SAR1869 912
SAR1870 1194
pckA 1593
SAR1874 480
SAR1875 258
SAR1876 1002
SAR1878 483
SAR1922 555
hemY 1401
hemH 924
hemE 1038
trap 504
SAR1927 1224
SAR1928 741
SAR1929 423
SAR1930 366
SAR1930a 189
SAR1933 942
SAR1934 2937
SAR1935 1197
SAR1936 345
SAR1937 1125
SAR1938 465
SAR1939 624
SAR1940 1113
SAR1941 822
citG 1386
SAR1943 396
SAR1944 153
SAR1945 600
SAR1946 471
SAR1947 1128
glnQ 729
SAR1950 1062
perR 447
SAR1952 951
SAR1953 453
SAR1954 1290
SAR1955 1095
SAR1956 1737
SAR1957 543
SAR1958 1038
SAR1959 978
SAR1960 837
SAR1961 1518
SAR1962 315
SAR1963 819
SAR1964 810
SAR1965 516
SAR1966 162
SAR1967 1152
SAR1968 531
SAR1969 1248
SAR1970 216
SAR1971 465
SAR1972 276
SAR1973 1218
SAR1974 630
vraS 1044
SAR1976 702
SAR1977 387
SAR1978 759
SAR1981 414
SAR1982 732
SAR1983 1314
SAR1984 501
SAR1985 555
SAR1986 1071
SAR1987 531
SAR1988 1362
SAR1989 948
gatB 1428
gatA 1458
gatC 303
putP 1539
SAR1995 1200
lig 2004
pcrA 2193
pcrB 693
SAR1999 303
purB 1296
SAR2001 1167
SAR2002 324
SAR2003 174
SAR2004 603
SAR2005 822
SAR2006 1470
SAR2010 1098
SAR2011 561
ppaC 936
SAR2013 1380
SAR2014 1029
SAR2015 402
SAR2016 174
SAR2017 1041
SAR2018 843
SAR2019 558
SAR2020 525
SAR2021 564
SAR2022 741
SAR2023 873
SAR2024 681
SAR2025 897
SAR2026 456
SAR2027 177
SAR2027a 99
SAR2028 1287
SAR2111 1308
groEL 1617
groES 285
SAR2118 744
SAR2121 786
hld 138
agrA 717
SAR2127 960
scrB 1485
scrR 951
SAR2130 1251
SAR2131 225
SAR2132 1080
SAR2133 636
SAR2134 1929
SAR2135 1611
SAR2136 1026
SAR2137 465
SAR2138 663
SAR2139 495
ilvB 1770
ilvH 255
ilvC 1005
leuA 1530
leuB 1047
leuC 1368
leuD 573
ilvA 1269
SAR2150 456
SAR2151 2151
sigB 771
rsbW 480
rsbV 327
rsbU 1002
SAR2156 363
SAR2157 171
alr 1149
acpS 360
SAR2160 492
SAR2161 1578
SAR2162 480
kdpC 561
kdpB 2028
kdpA 1677
kdpD 2658
kdpE2 696
SAR2168 1521
SAR2169 1359
SAR2170 1071
SAR2173 138
SAR2174 210
SAR2175 293
SAR2177 1485
SAR2178 648
SAR2179 873
thiM 792
thiD 831
tenA 690
SAR2184 696
SAR2185 396
SAR2186 441
fabZ 441
murA1 1266
SAR2189 234
atpC 405
atpD 1413
atpG 867
atpA 1509
atpH 540
atpF 522
atpE 213
atpB 729
atpI 354
mnaA 1134
upp 630
glyA 1239
SAR2202 525
SAR2203 420
SAR2204 1047
SAR2205 837
prfA 1077
SAR2207 600
rpmE 255
rho 1317
SAR2210 1428
SAR2211 339
murA2 1260
SAR2213 861
SAR2214 522
pyrG 1611
rpoE 531
SAR2217 861
SAR2218 804
SAR2219 672
SAR2220 1194
SAR2221 1185
SAR2223 351
pyn 1302
deoD2 711
SAR2227 444
SAR2228 414
SAR2229 1374
SAR2230 231
SAR2231 939
SAR2232 666
czrA 321
czrB 981
SAR2235 1092
SAR2240 858
SAR2241 783
glmS 1806
SAR2243 198
mtlA 1539
SAR2245 2133
SAR2252 1356
SAR2253 933
SAR2254 810
rocF 909
SAR2256 1065
SAR2257 1444
SAR2259 468
SAR2260 1344
SAR2261 684
SAR2262 1188
SAR2263 516
SAR2264 261
SAR2265 1371
SAR2268 984
SAR2269 1071
SAR2270 1758
SAR2271 1194
SAR2272 1977
asp23 510
SAR2274 240
SAR2275 537
opuD2 1563
SAR2277 1008
SAR2278 1005
SAR2279 870
lacG 1413
lacE 1713
lacF 312
lacD 981
lacB 516
lacA 429
lacR 756
SAR2288 732
SAR2290 849
SAR2291 417
SAR2295 426
SAR2296 705
SAR2297 1665
SAR2297b 183
SAR2298a 84
rpsI 393
rplM 438
SAR2302 795
SAR2303 807
SAR2304 861
SAR2305 810
rplQ 369
rpoA 945
rpsK 390
rpsM 366
rpmJ 114
infA 219
adk 648
secY 1293
rpmD 180
rplR 360
rplF 537
rpsH 399
rpsN 186
rplE 540
rplX 318
rplN 369
rpsQ 264
rpmC 210
rplP 435
rpsC 654
rplV 354
rpsS 279
rplB 834
rplW 276
rplC 663
rpsJ 309
SAR2337 396
SAR2338 1335
SAR2339 2136
SAR2340 888
glcU 864
SAR2342 909
SAR2343 165
SAR2344 318
SAR2345 3168
fmhB 1266
SAR2347 252
SAR2348 765
SAR2349 441
SAR2350 1212
SAR2351 351
moaA 1023
mobA 600
moaD 234
moaE 447
mobB 486
moeA 1260
moaC 495
moaB 507
moeB 1005
modC 606
modB 672
modA 783
SAR2364 798
SAR2365 771
SAR2366 555
SAR2367 942
SAR2368 909
SAR2369 1155
SAR2370 93
SAR2371 906
ureE 453
ureF 690
ureG 615
ureD 837
sarR 348
SAR2380 327
SAR2381 744
SAR2383 810
SAR2385 1401
SAR2386 1083
SAR2387 423
SAR2388 492
SAR2389 954
SAR2390 1125
SAR2391 777
SAR2391a 252
SAR2392 474
SAR2393 2955
SAR2394 948
SAR2395 798
SAR2396 693
SAR2397 738
SAR2398 330
SAR2399 873
SAR2400 1380
SAR2401 357
SAR2402 186
SAR2403 192
SAR2404 636
SAR2405 918
SAR2407 531
SAR2408 1605
SAR2409 765
SAR2410 507
SAR2411 1377
SAR2412 570
SAR2413 882
SAR2414 1122
hutI 1239
hutU 1662
SAR2418 885
SAR2420 936
SAR2421 1260
SAR2423 654
SAR2424 1020
SAR2425 327
SAR2426 1233
SAR2427 900
SAR2428 648
SAR2428a 123
SAR2428b 132
SAR2429 609
SAR2430 1209
fni 1050
SAR2432 948
SAR2433 492
SAR2434 420
SAR2435 921
SAR2436 639
SAR2437 1938
SAR2438 648
SAR2439 555
tcaB 1209
tcaA 1383
tcaR 456
SAR2444 969
SAR2445 666
SAR2446 1056
SAR2447 675
SAR2448 1374
SAR2449 444
SAR2450 456
mqo1 1536
lldP2 1599
SAR2456 1674
SAR2458 516
SAR2459 1005
SAR2460 402
SAR2461 1035
SAR2462 432
SAR2463 1278
SAR2464 624
SAR2465 945
scrA 1443
SAR2467 384
SAR2468 2106
SAR2469 423
gltT 1278
SAR2473 366
SAR2474 447
SAR2475 423
narT 1170
SAR2480 654
SAR2481 1035
SAR2482 453
narI 678
narJ 576
narH 1560
narG 3690
SAR2487 978
nasE 315
nasD 2406
SAR2490 753
SAR2491 537
SAR2495 468
SAR2496 1548
SAR2499 600
SAR2500 363
fmhA 1251
SAR2502 732
SAR2504 780
SAR2506 687
sbi 1314
hlgA 930
hlgC 948
hlgB 978
SAR2512 468
SAR2513 693
SAR2514 1116
bioB 1008
bioA 1359
SAR2517 687
SAR2518 1734
SAR2519 1785

In [4]:
core_lengths = np.array(core_lengths)
np.max(core_lengths), np.min(core_lengths), np.mean(core_lengths)

(np.int64(7176), np.int64(51), np.float64(902.2324760463944))

In [5]:
ref_path = Path("../data/staph/references")
ref_count = 0
ref_lengths = []

for fasta_file in ref_path.glob("*.fa"):
    print(f"--- Processing File: {fasta_file.name} ---")

    for record in SeqIO.parse(fasta_file, "fasta"):
        print(record.id, len(record.seq))
        ref_count += 1
        ref_lengths.append(len(record.seq))

print(f"Total number of reference sequences: {ref_count}")

--- Processing File: 04-02981.fa ---
gi|311222926|gb|CP001844.2| 2821452
--- Processing File: COL.fa ---
COL_all 2813862
--- Processing File: ED133.fa ---
gi|298693322|gb|CP001996.1| 2832478
--- Processing File: ED98.fa ---
ED98_all 2885262
--- Processing File: JH1.fa ---
JH1_all 2936936
--- Processing File: JH9.fa ---
JH9_all 2937129
--- Processing File: JKD6008.fa ---
gi|302749911|gb|CP002120.1| 2924344
--- Processing File: JKD6159.fa ---
JKD6159_all 2905992
--- Processing File: MSSA476.fa ---
MSSA476_all 2820454
--- Processing File: Mu50.fa ---
Mu50_all 2903636
--- Processing File: MW2.fa ---
MW2_all 2841116
--- Processing File: N315.fa ---
N315_all 2839469
--- Processing File: Newman.fa ---
gi|150373012|dbj|AP009351.1| 2878897
--- Processing File: R00000022.fa ---
gi|49240382|emb|BX571856.1| 2902619
--- Processing File: RF122.fa ---
gi|82655308|emb|AJ938182.1| 2742531
--- Processing File: RP62A.fa ---
gi|57865352|ref|NC_002976.3| 2616530
--- Processing File: S0385.fa ---
S0385_all 2885367
--- Processing File: TCH60.fa ---
TCH60_all 2827166
--- Processing File: TW20.fa ---
TW20_all 3075806
--- Processing File: USA300_FPR3757.fa ---
USA300_FPR3757_all 2917469
--- Processing File: USA300_TCH1516.fa ---
USA300_TCH1516_all 2903081
Total number of reference sequences: 21

In [6]:
ref_lengths = np.array(ref_lengths)
np.max(ref_lengths), np.min(ref_lengths), np.mean(ref_lengths)

(np.int64(3075806), np.int64(2616530), np.float64(2867218.8571428573))

In [7]:
all_genome_path = "../data/staph/all_genomes.fasta"
all_genome_count = 0

for record in SeqIO.parse(all_genome_path, "fasta"):
    print(record.id, len(record.seq))
    all_genome_count += 1

print(f"Total number of sequences: {all_genome_count}")

gi|311222926|gb|CP001844.2| 2821452
COL_all 2813862
gi|298693322|gb|CP001996.1| 2832478
ED98_all 2885262
JH1_all 2936936
JH9_all 2937129
gi|302749911|gb|CP002120.1| 2924344
JKD6159_all 2905992
MSSA476_all 2820454
MW2_all 2841116
Mu50_all 2903636
N315_all 2839469
gi|150373012|dbj|AP009351.1| 2878897
gi|49240382|emb|BX571856.1| 2902619
gi|82655308|emb|AJ938182.1| 2742531
gi|57865352|ref|NC_002976.3| 2616530
S0385_all 2885367
TCH60_all 2827166
TW20_all 3075806
USA300_FPR3757_all 2917469
USA300_TCH1516_all 2903081
C1075 2902619
C1076 2902619
C1077 2902619
C1078 2902619
C1079 2902619
C1080 2902619
C1081 2902619
C1082 2902619
C1083 2902619
C1084 2902619
C1085 2902619
C1087 2902619
C1088 2902619
C1089 2902619
C1090 2902619
C1091 2902619
C1092 2902619
C1093 2902619
C1094 2902619
C1095 2902619
C1096 2902619
C1097 2902619
C1098 2902619
C1099 2902619
C1100 2902619
C1101 2902619
C1102 2902619
C1103 2902619
C1104 2902619
C1105 2902619
C1106 2902619
C1107 2902619
C1108 2902619
C1110 2902619
C1111 2902619
C1112 2902619
C1113 2902619
C1114 2902619
C1115 2902619
C1116 2902619
C1117 2902619
C1118 2902619
C1119 2902619
C1120 2902619
C1121 2902619
C1122 2902619
C1123 2902619
C1124 2902619
C1125 2902619
C1126 2902619
C1127 2902619
C1128 2902619
C1129 2902619
C1130 2902619
C1131 2902619
C1132 2902619
C1134 2902619
C1135 2902619
C1136 2902619
C1137 2902619
C1139 2902619
C1140 2902619
C1141 2902619
C1142 2902619
C1143 2902619
C1144 2902619
C1146 2902619
C1147 2902619
C1148 2902619
C1149 2902619
C1150 2902619
C1151 2902619
C1152 2902619
C1153 2902619
C1154 2902619
C1155 2902619
C1156 2902619
C1157 2902619
C1158 2902619
C1159 2902619
C1160 2902619
C1161 2902619
C1162 2902619
C1163 2902619
C1164 2902619
C1165 2902619
C1274 2902619
C1275 2902619
C1276 2902619
C1277 2902619
C1278 2902619
C1279 2902619
C1280 2902619
C1281 2902619
C1282 2902619
C9655 2902619
C9656 2902619
C9657 2902619
C9658 2902619
C9659 2902619
C9660 2902619
C9662 2902619
C9663 2902619
C9664 2902619
C9665 2902619
C9666 2902619
C9667 2902619
C9668 2902619
C9669 2902619
C9670 2902620
Total number of sequences: 131

In [8]:
result_df = pd.read_csv('../data/staph/results.txt', sep='\t', header=None)
result_df

,0,1,2,3,4,5,6,7,8,9,10,11
0,dnaA,C9669,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
1,dnaA,C1281,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
2,dnaA,C1278,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
3,dnaA,C1275,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
4,dnaA,C1164,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
...,...,...,...,...,...,...,...,...,...,...,...,...
260482,rpmH,ED98_all,99.275,138,1,0,1,138,2824053,2824190,1.770000e-65,250.0
260483,rpmH,gi|298693322|gb|CP001996.1|,99.275,138,1,0,1,138,2832127,2832264,1.770000e-65,250.0
260484,rpmH,COL_all,99.275,138,1,0,1,138,2809098,2809235,1.770000e-65,250.0
260485,rpmH,gi|311222926|gb|CP001844.2|,99.275,138,1,0,1,138,2821101,2821238,1.770000e-65,250.0
260486,rpmH,gi|57865352|ref|NC_002976.3|,97.101,138,4,0,1,138,677,540,1.790000e-60,233.0

In [12]:
result_df.columns = ['Query_ID', 'Subject_ID', 'Identity', 'Alignment_Length', 'Mismatches',
                     'Gap_Openings', 'Query_Start', 'Query_End', 'Subject_Start', 'Subject_End',
                     'E-value', 'Bit_Score']
result_df

,Query_ID,Subject_ID,Identity,Alignment_Length,Mismatches,Gap_Openings,Query_Start,Query_End,Subject_Start,Subject_End,E-value,Bit_Score
0,dnaA,C9669,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
1,dnaA,C1281,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
2,dnaA,C1278,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
3,dnaA,C1275,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
4,dnaA,C1164,100.000,1362,0,0,1,1362,517,1878,0.000000e+00,2516.0
...,...,...,...,...,...,...,...,...,...,...,...,...
260482,rpmH,ED98_all,99.275,138,1,0,1,138,2824053,2824190,1.770000e-65,250.0
260483,rpmH,gi|298693322|gb|CP001996.1|,99.275,138,1,0,1,138,2832127,2832264,1.770000e-65,250.0
260484,rpmH,COL_all,99.275,138,1,0,1,138,2809098,2809235,1.770000e-65,250.0
260485,rpmH,gi|311222926|gb|CP001844.2|,99.275,138,1,0,1,138,2821101,2821238,1.770000e-65,250.0
260486,rpmH,gi|57865352|ref|NC_002976.3|,97.101,138,4,0,1,138,677,540,1.790000e-60,233.0

In [14]:
np.unique(result_df[['Query_ID']])

array(['SAR0003', 'SAR0007', 'SAR0010', ..., 'yycJ', 'zur', 'zwf'],
      shape=(1983,), dtype=object)

In [16]:
np.unique(result_df[['Subject_ID']]).shape

(131,)

In [26]:
np.where(result_df.duplicated(subset=['Query_ID', 'Subject_ID']))

(array([  4304,   4306,   4308, ..., 250970, 253718, 253720], shape=(2313,)),)

In [28]:
result_df[4303:4310]

,Query_ID,Subject_ID,Identity,Alignment_Length,Mismatches,Gap_Openings,Query_Start,Query_End,Subject_Start,Subject_End,E-value,Bit_Score
4303,lldP1,C1281,100.000,1593,0,0,1,1593,121907,123499,0.000000e+00,2942.0
4304,lldP1,C1281,74.667,675,153,16,22,687,2525936,2525271,2.420000e-74,283.0
4305,lldP1,C1278,100.000,1593,0,0,1,1593,121907,123499,0.000000e+00,2942.0
4306,lldP1,C1278,74.667,675,153,16,22,687,2525936,2525271,2.420000e-74,283.0
4307,lldP1,C1159,100.000,1593,0,0,1,1593,121907,123499,0.000000e+00,2942.0
4308,lldP1,C1159,74.667,675,153,16,22,687,2525936,2525271,2.420000e-74,283.0
4309,lldP1,C1156,100.000,1593,0,0,1,1593,121907,123499,0.000000e+00,2942.0

Select segments from genome only in `saureus.fa`.
- duplicate: pick the best matched one
- missing: print a message

In [33]:
df_filtered = result_df[result_df['Query_ID'] == 'dnaA'].copy()
df_filtered

,Query_ID,Subject_ID,Identity,Alignment_Length,Mismatches,Gap_Openings,Query_Start,Query_End,Subject_Start,Subject_End,E-value,Bit_Score
0,dnaA,C9669,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
1,dnaA,C1281,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
2,dnaA,C1278,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
3,dnaA,C1275,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
4,dnaA,C1164,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
...,...,...,...,...,...,...,...,...,...,...,...,...
125,dnaA,JH1_all,99.119,1362,12,0,1,1362,641,2002,0.0,2449.0
126,dnaA,ED98_all,99.119,1362,12,0,1,1362,517,1878,0.0,2449.0
127,dnaA,gi|311222926|gb|CP001844.2|,99.119,1362,12,0,1,1362,517,1878,0.0,2449.0
128,dnaA,MW2_all,99.046,1362,13,0,1,1362,517,1878,0.0,2444.0
129,dnaA,MSSA476_all,99.046,1362,13,0,1,1362,517,1878,0.0,2444.0

In [34]:
df_sorted = df_filtered.sort_values(by='Bit_Score', ascending=False)
df_best = df_sorted.drop_duplicates(subset='Subject_ID', keep='first')

In [36]:
df_best

,Query_ID,Subject_ID,Identity,Alignment_Length,Mismatches,Gap_Openings,Query_Start,Query_End,Subject_Start,Subject_End,E-value,Bit_Score
0,dnaA,C9669,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
1,dnaA,C1281,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
2,dnaA,C1278,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
3,dnaA,C1275,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
4,dnaA,C1164,100.000,1362,0,0,1,1362,517,1878,0.0,2516.0
...,...,...,...,...,...,...,...,...,...,...,...,...
125,dnaA,JH1_all,99.119,1362,12,0,1,1362,641,2002,0.0,2449.0
126,dnaA,ED98_all,99.119,1362,12,0,1,1362,517,1878,0.0,2449.0
127,dnaA,gi|311222926|gb|CP001844.2|,99.119,1362,12,0,1,1362,517,1878,0.0,2449.0
128,dnaA,MW2_all,99.046,1362,13,0,1,1362,517,1878,0.0,2444.0
129,dnaA,MSSA476_all,99.046,1362,13,0,1,1362,517,1878,0.0,2444.0