# Load and process Klebsiella pneumoniae data

In [1]:
import numpy as np
import pandas as pd
from Bio import AlignIO, Phylo
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align import MultipleSeqAlignment
from tqdm import tqdm
import sys
sys.path.append('../pysimARG')
from segment_summary_stats import segment_summary_stats
from clonal_genealogy import ClonalTree

## Load and check `.aln` data

In [2]:
def remove_gap_columns(alignment_block):
    """
    Takes a Biopython MultipleSeqAlignment block and returns a new block
    with any column containing '-', '.', 'N', or 'n' completely removed,
    along with the list of valid column indices within this block.
    """
    align_len = alignment_block.get_alignment_length()

    invalid_chars = {'N', 'n', '-', '.'}
    
    valid_columns = [
        i for i in range(align_len) 
        if not any(char in alignment_block[:, i] for char in invalid_chars)
    ]

    cleaned_records = []
    for record in alignment_block:
        clean_seq_string = "".join([record.seq[i] for i in valid_columns])
        new_record = SeqRecord(Seq(clean_seq_string), id=record.id, description="")
        cleaned_records.append(new_record)

    # Now returning a tuple of (cleaned_alignment, valid_indices)
    return MultipleSeqAlignment(cleaned_records), valid_columns

In [3]:
def process_alignment_in_blocks(full_alignment, block_size=10000):
    """
    Slices a massive alignment into smaller blocks, cleans them using 
    remove_gap_columns(), and glues them back together. 
    Returns the cleaned alignment and a list mapping clean_index -> raw_index.
    """
    total_len = full_alignment.get_alignment_length()
    final_alignment = None
    
    # Map: clean_index -> raw_index
    position_mapping = []
    
    for start in tqdm(range(0, total_len, block_size), desc="processing alignment blocks"):
        end = min(start + block_size, total_len)
        sub_block = full_alignment[:, start:end]
        cleaned_block, valid_cols = remove_gap_columns(sub_block)

        if cleaned_block.get_alignment_length() > 0:
            if final_alignment is None:
                final_alignment = cleaned_block
            else:
                final_alignment += cleaned_block
            
            # Shift the valid block indices by the 'start' offset of the current block
            # and append them to global mapping.
            position_mapping.extend([col + start for col in valid_cols])
                
    return final_alignment, position_mapping

In [4]:
seq_path = "../data/klebsiella/noref.aln"
raw_alignment = AlignIO.read(seq_path, "fasta")

print("Alignment summary:")
print(raw_alignment)
print("-" * 40)

seq_count = 0
seq_names = []

for record in raw_alignment:
    print(record.id, len(record.seq))
    seq_names.append(record.id)
    seq_count += 1

print(f"Total number of sequences: {seq_count}")

Alignment summary:
Alignment with 100 rows and 5280085 columns
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 19UUUUQvAAyHsrWsprUbF7-GCA_019927745
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 1CCAAZiMef1Wi3JBZomcfi-GCA_019928075
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 1J25vPYcr5cWPUCJFGcaYk-GCA_019928505
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 1NBFH6Ut6cUUtx6LSWophX-GCA_019927505
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 1jxgrGNJjS7terz8orucSc-GCA_019927405
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 1k2mmojDYi7HwWwByEje5E-GCA_019928115
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 2vb3nFYf4FyUm6srAtv2QZ-GCA_019930305
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 35JJmVwexb5WeHSxNcpWqb-GCA_020407065
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 3JR2tMy7o1jC2oFuU8nHzv-GCA_019930175
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 3Z26tDKznNidwX8jD2CCXz-GCA_019927605
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 3mN8TuYT3jHUeUgeizumoH-GCA_019927945
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 4LWwBRkiJbJ9VRrwtXTnqQ-GCA_019927965
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 5FvsUoVVZcDdVsBjEr1Umn-GCA_019930345
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 5GC8opk2MbYwiY497SxJnj-GCA_019927625
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 5THeZZkUULnf1YDL2NkVLt-GCA_019927385
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 5VC9fx9FUjEYHZ1FBhaRK6-GCA_019927855
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 5rzNEErwwW9sBnVoSPeLxJ-GCA_019927845
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC 5wFKBtMW672BZSS5V4YHyi-GCA_019928465
...
GTGTCACTTTCGCTTTGGCAGCAGTGTCTTGCCCGATTGCAGGA...GCC xaAjEgiWJ6VpYxwkH9LSk9-GCA_019928595
----------------------------------------
19UUUUQvAAyHsrWsprUbF7-GCA_019927745 5280085
1CCAAZiMef1Wi3JBZomcfi-GCA_019928075 5280085
1J25vPYcr5cWPUCJFGcaYk-GCA_019928505 5280085
1NBFH6Ut6cUUtx6LSWophX-GCA_019927505 5280085
1jxgrGNJjS7terz8orucSc-GCA_019927405 5280085
1k2mmojDYi7HwWwByEje5E-GCA_019928115 5280085
2vb3nFYf4FyUm6srAtv2QZ-GCA_019930305 5280085
35JJmVwexb5WeHSxNcpWqb-GCA_020407065 5280085
3JR2tMy7o1jC2oFuU8nHzv-GCA_019930175 5280085
3Z26tDKznNidwX8jD2CCXz-GCA_019927605 5280085
3mN8TuYT3jHUeUgeizumoH-GCA_019927945 5280085
4LWwBRkiJbJ9VRrwtXTnqQ-GCA_019927965 5280085
5FvsUoVVZcDdVsBjEr1Umn-GCA_019930345 5280085
5GC8opk2MbYwiY497SxJnj-GCA_019927625 5280085
5THeZZkUULnf1YDL2NkVLt-GCA_019927385 5280085
5VC9fx9FUjEYHZ1FBhaRK6-GCA_019927855 5280085
5rzNEErwwW9sBnVoSPeLxJ-GCA_019927845 5280085
5wFKBtMW672BZSS5V4YHyi-GCA_019928465 5280085
6HH3q8XbyBMDeCBfHFK8i1-GCA_019928065 5280085
6K89HyFBbDwXdwchwqkADP-GCA_019928025 5280085
6ht9W7ffLLQDheuAYEQ5C7-GCA_019928345 5280085
6zQJeJPfAM34HV5z2gbV8g-GCA_019930285 5280085
7iUximMjZSb8j3oo5o3GyN-GCA_019927325 5280085
7vYZV2y3zKy85RBEoAfA5p-GCA_019928325 5280085
7w3irBsjXvt8VfLewn9R4Q-GCA_019930055 5280085
82xUEqwFKMgQG1m71oAhsG-GCA_019927645 5280085
8vqqvtCFEZ7gvHmzpWg56E-GCA_019930465 5280085
99gGmGyfpzkc3vFSULEvRx-GCA_019927585 5280085
9gqhpN2rYKHQdHPw9JTQ2H-GCA_019927565 5280085
9q65eWWCftTAeLuvaw63T8-GCA_019927525 5280085
a6rxHWfUQC9dZEewstn69G-GCA_019927535 5280085
a8vzRodf4aL8yyTWsFaDzj-GCA_019930355 5280085
aLK9AZNvhf2zrCjNDKAf3Y-GCA_019927725 5280085
aPo1WT7vwvKNVMiXsDCPRE-GCA_019930165 5280085
aTa52EeYEuHBS3RnkdG3Pz-GCA_019928585 5280085
at7WT1sjMVWMd3ZduT1c48-GCA_019930445 5280085
az414Kup8wLMB9EDR6e8SP-GCA_019927805 5280085
azpE7ep1YFkeRDdSxTwk2m-GCA_019928165 5280085
b4CdTaqeqvZ8ooCqG9ai6b-GCA_020406995 5280085
b6JtuUFHKWBJXW9LmHhryc-GCA_019930085 5280085
bKMwQNtdgmF9bNgpmS6FdT-GCA_019927905 5280085
bXsDbJWn7tJqKSRYMvjx9N-GCA_019928445 5280085
bhU1QCecryLyfRxY4U5evf-GCA_019927785 5280085
c4euKzgbdbwp3QiAaTdp5e-GCA_019928305 5280085
c7SgGjGJH4cXsbVZPk1KJL-GCA_019927465 5280085
cdSc4jDbDw4No7pWi4bpq1-GCA_019927345 5280085
dTn8XifioDNmfA2hkdDMhW-GCA_020407035 5280085
dxgXm3Rqnjc69nfmRMWCQj-GCA_019930325 5280085
e8JzZPYJLGyK7fBysQZ1xP-GCA_020407015 5280085
e9hwYHy1tPuGCxcmNNgnWp-GCA_019928365 5280085
eCBCcFiGhdpp2uKzSE6wF6-GCA_019930225 5280085
eLZocCvzHAm5ADYkAM6Zge-GCA_019930505 5280085
egVzbfQQTKqSiMtu588vfY-GCA_019928385 5280085
ehfPkFL4CpRgJqT8hCEU1k-GCA_019930405 5280085
f4FwSD1buXV3PSWZTmYgsy-GCA_019930425 5280085
f5HyGPQn1fhP2aBKuPXmbA-GCA_019930145 5280085
g3Dbk11JkCHozHc7bZNHjW-GCA_019927825 5280085
gU7Egkk1qHtGXgyxfyCkVV-GCA_019927265 5280085
hKX9WQm8NWVSdxyAYSH5Lb-GCA_019927925 5280085
iCQDoKrdwWSUJojbcEM9om-GCA_019928545 5280085
iLMuekiRdnvHRZh49qziYJ-GCA_019928685 5280085
imXvjQtAnAa1TVMzX2Vfje-GCA_019930265 5280085
jVVveb9PTjGTpyrMhUCsDg-GCA_019927285 5280085
kPkr31VBxVn4KFAHm1V8AJ-GCA_019928215 5280085
kbcAPqvMwtWAP944VTcemk-GCA_019928625 5280085
kgzgfQBjjzr937K9PRDYUn-GCA_019927435 5280085
mJbyRAFsEovdeC7eSP9PEx-GCA_019928245 5280085
n1M1mCdML4q4oaRYYaq2Ca-GCA_020407045 5280085
nEcqLYZ1wYJEmVESjVduz1-GCA_019928185 5280085
nG7QbfuE6G6yvfHQNmiHrW-GCA_019930185 5280085
nSFymoP4AQEsMnKgY82Syr-GCA_019928285 5280085
nfqCJMhzeHPiYcoQeAh5x8-GCA_019927305 5280085
o3RhFr5btpW7DTfXtue7c5-GCA_019927485 5280085
oHcP3E8cng1JUjghDLD6DG-GCA_019927705 5280085
oWLnzP69hAEYw4wJcDNKkq-GCA_019928565 5280085
p1hNqptED8kubPGG2AhE28-GCA_019927315 5280085
pVybzfzKoAGacFHHpXyyko-GCA_019928045 5280085
qMcWTwZ6PpzR5ZyecnjEn9-GCA_019927985 5280085
qVSVdknxffkG4oMCzjCU1M-GCA_019928205 5280085
qyphhfakZqxCXk1XemPcqm-GCA_019930125 5280085
rDGuDcKqkxKSEUEbjD7YW5-GCA_019928525 5280085
s4xBWyFXE1ndobK6nvpby9-GCA_019930385 5280085
sNoisCM5QEAzeW6HuTyrbZ-GCA_019928405 5280085
spc6uUrrN2v9jc6UX7DiRy-GCA_019930485 5280085
t24foafBhtqEpQzqBTqgbw-GCA_019928635 5280085
t6sXGZCZ8T4e7B2tgE2CDz-GCA_019928005 5280085
tAde7EEq7iaJN7D7nKB2E1-GCA_019928145 5280085
tFFXfZQijookHqDT8i3ZFc-GCA_019927885 5280085
tLVH4GxhdsMA9qFp49eezd-GCA_019928395 5280085
tQcvNEu2HcGi5pNnnfK5g2-GCA_019927425 5280085
txUHDpNkVwqoqw8F4gEgJQ-GCA_019927765 5280085
u5oWrqfAGj5r2tPuK2v97v-GCA_019928705 5280085
u9tWDXSuB1juFfAV2KcFv8-GCA_019928105 5280085
uVyaKVcPzWxgxSZ6ogw95S-GCA_019928265 5280085
uqeVjytTQfqfm59bQQLFcz-GCA_019927685 5280085
w7tJjbUBPZePmFG3NDmzp5-GCA_019928665 5280085
w8dqW4oBbGroQ1WLdJoyLD-GCA_019930245 5280085
wZab6G2qfpNKCbZcpoCFMA-GCA_019928485 5280085
wyLzoBt5Tjc59xkPvGkRuT-GCA_019927655 5280085
xaAjEgiWJ6VpYxwkH9LSk9-GCA_019928595 5280085
Total number of sequences: 100

In [5]:
alignment, clean_to_raw_map = process_alignment_in_blocks(raw_alignment, block_size=50000)

print("Alignment summary:")
print(alignment)
print("-" * 40)

seq_count = 0
seq_names = []

for record in alignment:
    print(record.id, len(record.seq))
    seq_names.append(record.id)
    seq_count += 1

print(f"Total number of sequences: {seq_count}")

processing alignment blocks: 100%|██████████| 106/106 [27:17<00:00, 15.44s/it]

Alignment summary:
Alignment with 100 rows and 3761346 columns
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 19UUUUQvAAyHsrWsprUbF7-GCA_019927745
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 1CCAAZiMef1Wi3JBZomcfi-GCA_019928075
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 1J25vPYcr5cWPUCJFGcaYk-GCA_019928505
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 1NBFH6Ut6cUUtx6LSWophX-GCA_019927505
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 1jxgrGNJjS7terz8orucSc-GCA_019927405
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 1k2mmojDYi7HwWwByEje5E-GCA_019928115
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 2vb3nFYf4FyUm6srAtv2QZ-GCA_019930305
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 35JJmVwexb5WeHSxNcpWqb-GCA_020407065
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 3JR2tMy7o1jC2oFuU8nHzv-GCA_019930175
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 3Z26tDKznNidwX8jD2CCXz-GCA_019927605
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 3mN8TuYT3jHUeUgeizumoH-GCA_019927945
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 4LWwBRkiJbJ9VRrwtXTnqQ-GCA_019927965
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 5FvsUoVVZcDdVsBjEr1Umn-GCA_019930345
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 5GC8opk2MbYwiY497SxJnj-GCA_019927625
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 5THeZZkUULnf1YDL2NkVLt-GCA_019927385
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 5VC9fx9FUjEYHZ1FBhaRK6-GCA_019927855
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 5rzNEErwwW9sBnVoSPeLxJ-GCA_019927845
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG 5wFKBtMW672BZSS5V4YHyi-GCA_019928465
...
GCGATAACACGCTGGCACTGTATGCGCCAAACCGTTTTGTGCTC...CAG xaAjEgiWJ6VpYxwkH9LSk9-GCA_019928595
----------------------------------------
19UUUUQvAAyHsrWsprUbF7-GCA_019927745 3761346
1CCAAZiMef1Wi3JBZomcfi-GCA_019928075 3761346
1J25vPYcr5cWPUCJFGcaYk-GCA_019928505 3761346
1NBFH6Ut6cUUtx6LSWophX-GCA_019927505 3761346
1jxgrGNJjS7terz8orucSc-GCA_019927405 3761346
1k2mmojDYi7HwWwByEje5E-GCA_019928115 3761346
2vb3nFYf4FyUm6srAtv2QZ-GCA_019930305 3761346
35JJmVwexb5WeHSxNcpWqb-GCA_020407065 3761346
3JR2tMy7o1jC2oFuU8nHzv-GCA_019930175 3761346
3Z26tDKznNidwX8jD2CCXz-GCA_019927605 3761346
3mN8TuYT3jHUeUgeizumoH-GCA_019927945 3761346
4LWwBRkiJbJ9VRrwtXTnqQ-GCA_019927965 3761346
5FvsUoVVZcDdVsBjEr1Umn-GCA_019930345 3761346
5GC8opk2MbYwiY497SxJnj-GCA_019927625 3761346
5THeZZkUULnf1YDL2NkVLt-GCA_019927385 3761346
5VC9fx9FUjEYHZ1FBhaRK6-GCA_019927855 3761346
5rzNEErwwW9sBnVoSPeLxJ-GCA_019927845 3761346
5wFKBtMW672BZSS5V4YHyi-GCA_019928465 3761346
6HH3q8XbyBMDeCBfHFK8i1-GCA_019928065 3761346
6K89HyFBbDwXdwchwqkADP-GCA_019928025 3761346
6ht9W7ffLLQDheuAYEQ5C7-GCA_019928345 3761346
6zQJeJPfAM34HV5z2gbV8g-GCA_019930285 3761346
7iUximMjZSb8j3oo5o3GyN-GCA_019927325 3761346
7vYZV2y3zKy85RBEoAfA5p-GCA_019928325 3761346
7w3irBsjXvt8VfLewn9R4Q-GCA_019930055 3761346
82xUEqwFKMgQG1m71oAhsG-GCA_019927645 3761346
8vqqvtCFEZ7gvHmzpWg56E-GCA_019930465 3761346
99gGmGyfpzkc3vFSULEvRx-GCA_019927585 3761346
9gqhpN2rYKHQdHPw9JTQ2H-GCA_019927565 3761346
9q65eWWCftTAeLuvaw63T8-GCA_019927525 3761346
a6rxHWfUQC9dZEewstn69G-GCA_019927535 3761346
a8vzRodf4aL8yyTWsFaDzj-GCA_019930355 3761346
aLK9AZNvhf2zrCjNDKAf3Y-GCA_019927725 3761346
aPo1WT7vwvKNVMiXsDCPRE-GCA_019930165 3761346
aTa52EeYEuHBS3RnkdG3Pz-GCA_019928585 3761346
at7WT1sjMVWMd3ZduT1c48-GCA_019930445 3761346
az414Kup8wLMB9EDR6e8SP-GCA_019927805 3761346
azpE7ep1YFkeRDdSxTwk2m-GCA_019928165 3761346
b4CdTaqeqvZ8ooCqG9ai6b-GCA_020406995 3761346
b6JtuUFHKWBJXW9LmHhryc-GCA_019930085 3761346
bKMwQNtdgmF9bNgpmS6FdT-GCA_019927905 3761346
bXsDbJWn7tJqKSRYMvjx9N-GCA_019928445 3761346
bhU1QCecryLyfRxY4U5evf-GCA_019927785 3761346
c4euKzgbdbwp3QiAaTdp5e-GCA_019928305 3761346
c7SgGjGJH4cXsbVZPk1KJL-GCA_019927465 3761346
cdSc4jDbDw4No7pWi4bpq1-GCA_019927345 3761346
dTn8XifioDNmfA2hkdDMhW-GCA_020407035 3761346
dxgXm3Rqnjc69nfmRMWCQj-GCA_019930325 3761346
e8JzZPYJLGyK7fBysQZ1xP-GCA_020407015 3761346
e9hwYHy1tPuGCxcmNNgnWp-GCA_019928365 3761346
eCBCcFiGhdpp2uKzSE6wF6-GCA_019930225 3761346
eLZocCvzHAm5ADYkAM6Zge-GCA_019930505 3761346
egVzbfQQTKqSiMtu588vfY-GCA_019928385 3761346
ehfPkFL4CpRgJqT8hCEU1k-GCA_019930405 3761346
f4FwSD1buXV3PSWZTmYgsy-GCA_019930425 3761346
f5HyGPQn1fhP2aBKuPXmbA-GCA_019930145 3761346
g3Dbk11JkCHozHc7bZNHjW-GCA_019927825 3761346
gU7Egkk1qHtGXgyxfyCkVV-GCA_019927265 3761346
hKX9WQm8NWVSdxyAYSH5Lb-GCA_019927925 3761346
iCQDoKrdwWSUJojbcEM9om-GCA_019928545 3761346
iLMuekiRdnvHRZh49qziYJ-GCA_019928685 3761346
imXvjQtAnAa1TVMzX2Vfje-GCA_019930265 3761346
jVVveb9PTjGTpyrMhUCsDg-GCA_019927285 3761346
kPkr31VBxVn4KFAHm1V8AJ-GCA_019928215 3761346
kbcAPqvMwtWAP944VTcemk-GCA_019928625 3761346
kgzgfQBjjzr937K9PRDYUn-GCA_019927435 3761346
mJbyRAFsEovdeC7eSP9PEx-GCA_019928245 3761346
n1M1mCdML4q4oaRYYaq2Ca-GCA_020407045 3761346
nEcqLYZ1wYJEmVESjVduz1-GCA_019928185 3761346
nG7QbfuE6G6yvfHQNmiHrW-GCA_019930185 3761346
nSFymoP4AQEsMnKgY82Syr-GCA_019928285 3761346
nfqCJMhzeHPiYcoQeAh5x8-GCA_019927305 3761346
o3RhFr5btpW7DTfXtue7c5-GCA_019927485 3761346
oHcP3E8cng1JUjghDLD6DG-GCA_019927705 3761346
oWLnzP69hAEYw4wJcDNKkq-GCA_019928565 3761346
p1hNqptED8kubPGG2AhE28-GCA_019927315 3761346
pVybzfzKoAGacFHHpXyyko-GCA_019928045 3761346
qMcWTwZ6PpzR5ZyecnjEn9-GCA_019927985 3761346
qVSVdknxffkG4oMCzjCU1M-GCA_019928205 3761346
qyphhfakZqxCXk1XemPcqm-GCA_019930125 3761346
rDGuDcKqkxKSEUEbjD7YW5-GCA_019928525 3761346
s4xBWyFXE1ndobK6nvpby9-GCA_019930385 3761346
sNoisCM5QEAzeW6HuTyrbZ-GCA_019928405 3761346
spc6uUrrN2v9jc6UX7DiRy-GCA_019930485 3761346
t24foafBhtqEpQzqBTqgbw-GCA_019928635 3761346
t6sXGZCZ8T4e7B2tgE2CDz-GCA_019928005 3761346
tAde7EEq7iaJN7D7nKB2E1-GCA_019928145 3761346
tFFXfZQijookHqDT8i3ZFc-GCA_019927885 3761346
tLVH4GxhdsMA9qFp49eezd-GCA_019928395 3761346
tQcvNEu2HcGi5pNnnfK5g2-GCA_019927425 3761346
txUHDpNkVwqoqw8F4gEgJQ-GCA_019927765 3761346
u5oWrqfAGj5r2tPuK2v97v-GCA_019928705 3761346
u9tWDXSuB1juFfAV2KcFv8-GCA_019928105 3761346
uVyaKVcPzWxgxSZ6ogw95S-GCA_019928265 3761346
uqeVjytTQfqfm59bQQLFcz-GCA_019927685 3761346
w7tJjbUBPZePmFG3NDmzp5-GCA_019928665 3761346
w8dqW4oBbGroQ1WLdJoyLD-GCA_019930245 3761346
wZab6G2qfpNKCbZcpoCFMA-GCA_019928485 3761346
wyLzoBt5Tjc59xkPvGkRuT-GCA_019927655 3761346
xaAjEgiWJ6VpYxwkH9LSk9-GCA_019928595 3761346
Total number of sequences: 100

## Trace back to raw sequence positions

### `rand_seg_df`

In [13]:
rand_seg_df = pd.read_csv("../data/klebsiella/rand_seg_info.csv")
rand_seg_df['Gene_Length_raw'] = None
rand_seg_df['Start_pos_raw'] = None
rand_seg_df['End_pos_raw'] = None
rand_seg_df.head()

,Gene_Length,Start_pos,End_pos,Alignment,Gene_Length_raw,Start_pos_raw,End_pos_raw
0,1000,1873417,1874416,True,None,None,None
1,1000,1104665,1105664,True,None,None,None
2,1000,210756,211755,True,None,None,None
3,1000,2961240,2962239,True,None,None,None
4,1000,65616,66615,True,None,None,None

In [14]:
for i in range(rand_seg_df.shape[0]):
    start_pos_clean = rand_seg_df.loc[i, 'Start_pos']
    end_pos_clean = rand_seg_df.loc[i, 'End_pos']
    
    rand_seg_df.loc[i, 'Start_pos_raw'] = clean_to_raw_map[start_pos_clean - 1] + 1
    rand_seg_df.loc[i, 'End_pos_raw'] = clean_to_raw_map[end_pos_clean - 1] + 1
    rand_seg_df.loc[i, 'Gene_Length_raw'] = rand_seg_df.loc[i, 'End_pos_raw'] - rand_seg_df.loc[i, 'Start_pos_raw'] + 1

print(rand_seg_df.head())
rand_seg_df.to_csv("../data/klebsiella/rand_seg_info_updated.csv", index=False)

   Gene_Length  Start_pos  End_pos  Alignment Gene_Length_raw Start_pos_raw  \
0         1000    1873417  1874416       True            1000       2407524
1         1000    1104665  1105664       True            1000       1372809
2         1000     210756   211755       True            1000        269646
3         1000    2961240  2962239       True            1000       4233501
4         1000      65616    66615       True            1001         69950

  End_pos_raw
0     2408523
1     1373808
2      270645
3     4234500
4       70950

### `rand_seg_df2`

In [16]:
rand_seg_df2 = pd.read_csv("../data/klebsiella/rand_seg_info2.csv")
rand_seg_df2['Gene_Length_raw'] = None
rand_seg_df2['Start_pos_raw'] = None
rand_seg_df2['End_pos_raw'] = None
rand_seg_df2.head()

,Gene_Length,Start_pos,End_pos,Alignment,Gene_Length_raw,Start_pos_raw,End_pos_raw
0,7036,1873417,1880452,True,None,None,None
1,8139,210756,218894,True,None,None,None
2,179,2961240,2961418,True,None,None,None
3,450,212913,213362,True,None,None,None
4,4249,1980341,1984589,True,None,None,None

In [17]:
for i in range(rand_seg_df2.shape[0]):
    start_pos_clean = rand_seg_df2.loc[i, 'Start_pos']
    end_pos_clean = rand_seg_df2.loc[i, 'End_pos']
    
    rand_seg_df2.loc[i, 'Start_pos_raw'] = clean_to_raw_map[start_pos_clean - 1] + 1
    rand_seg_df2.loc[i, 'End_pos_raw'] = clean_to_raw_map[end_pos_clean - 1] + 1
    rand_seg_df2.loc[i, 'Gene_Length_raw'] = rand_seg_df2.loc[i, 'End_pos_raw'] - rand_seg_df2.loc[i, 'Start_pos_raw'] + 1

print(rand_seg_df2.head())
rand_seg_df2.to_csv("../data/klebsiella/rand_seg_info2_updated.csv", index=False)

   Gene_Length  Start_pos  End_pos  Alignment Gene_Length_raw Start_pos_raw  \
0         7036    1873417  1880452       True            8436       2407524
1         8139     210756   218894       True            8772        269646
2          179    2961240  2961418       True             179       4233501
3          450     212913   213362       True             451        272414
4         4249    1980341  1984589       True            4251       2739453

  End_pos_raw
0     2415959
1      278417
2     4233679
3      272864
4     2743703